"""codegen subcommands: local, model-free artifact generators."""
from __future__ import annotations

from pathlib import Path
from typing import Optional

import typer

from bewley.commands.common import HumanOption, fail, finish, get_project, should_emit_json
from bewley.project import BewleyError, _build_theory_explorer_script

app = typer.Typer(help="Generate local artifact-rendering scripts (no model execution).")


def _feedback_insights_makefile(model: str, seed: int, bundle_size: int, coverage: int) -> str:
    return f'''# Generated by `bewley codegen makefile --workflow feedback-insights`.
# Regenerate this file instead of editing workflow targets by hand.
# Paid inference is intentionally exposed only through explicit `*-run` targets.
BEWLEY ?= bewley
MODEL ?= {model}
SEED ?= {seed}
BUNDLE_SIZE ?= {bundle_size}
COVERAGE ?= {coverage}

.PHONY: help next discovery-jobs discovery-run discovery-ingest consolidation-jobs consolidation-run consolidation-ingest classification-jobs classification-run classification-ingest aggregate explorer check

help:
\t@echo "Feedback insights: discovery -> consolidation -> classification -> report"
\t@echo "Run 'make next' between material stages. Targets ending in -run are paid."

next:
\t$(BEWLEY) next

discovery-jobs:
\t$(BEWLEY) insights discover jobs --seed $(SEED) --bundle-size $(BUNDLE_SIZE) --coverage $(COVERAGE) --model $(MODEL) --output runs/001-discovery/jobs.ep

discovery-run:
\t@echo "PAID EXTERNAL STEP: bundled candidate-code discovery"
\tep run --jobs runs/001-discovery/jobs.ep --model_list runs/001-discovery/models.json --output runs/001-discovery/results.ep

discovery-ingest:
\t$(BEWLEY) insights discover ingest runs/001-discovery/results.ep --jobs runs/001-discovery/jobs.ep
\t$(BEWLEY) next

consolidation-jobs:
\t$(BEWLEY) insights consolidate jobs --candidates runs/001-discovery/candidates.jsonl --model $(MODEL) --output runs/002-consolidation/jobs.ep --min-codes 8 --max-codes 20

consolidation-run:
\t@echo "PAID EXTERNAL STEP: global candidate consolidation"
\tep run --jobs runs/002-consolidation/jobs.ep --model_list runs/002-consolidation/models.json --output runs/002-consolidation/results.ep

consolidation-ingest:
\t$(BEWLEY) insights consolidate ingest runs/002-consolidation/results.ep --jobs runs/002-consolidation/jobs.ep
\t$(BEWLEY) next

classification-jobs:
\t$(BEWLEY) insights classify jobs --model $(MODEL) --output runs/003-classification/jobs.ep

classification-run:
\t@echo "PAID EXTERNAL STEP: exhaustive response classification"
\tep run --jobs runs/003-classification/jobs.ep --model_list runs/003-classification/models.json --output runs/003-classification/results.ep

classification-ingest:
\t$(BEWLEY) insights classify ingest runs/003-classification/results.ep --jobs runs/003-classification/jobs.ep
\t$(BEWLEY) next

aggregate:
\t$(BEWLEY) insights aggregate

explorer:
\t$(BEWLEY) insights evidence-export

check:
\t$(BEWLEY) fsck
'''


@app.command("makefile")
def codegen_makefile(
    workflow: str = typer.Option(..., "--workflow", help="Workflow template; currently feedback-insights."),
    output: Path = typer.Option(Path("Makefile"), "--output", "-o"),
    model: str = typer.Option("gpt-5-mini", "--model"),
    seed: int = typer.Option(20260803, "--seed"),
    bundle_size: int = typer.Option(25, "--bundle-size", min=5, max=100),
    coverage: int = typer.Option(2, "--coverage", min=1, max=5),
    force: bool = typer.Option(False, "--force"),
    human: bool = HumanOption,
) -> None:
    """Generate an executable Make runbook with explicit paid boundaries."""
    command, json_flag = "codegen makefile", should_emit_json(human)
    project = get_project(command, json_flag)
    try:
        if workflow != "feedback-insights":
            raise BewleyError(f"unknown workflow: {workflow}", code="INVALID_INPUT")
        target = output if output.is_absolute() else project.root / output
        if target.exists() and not force:
            raise BewleyError(f"{target} already exists", code="ALREADY_EXISTS")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_feedback_insights_makefile(model, seed, bundle_size, coverage), encoding="utf-8")
        result = {
            "workflow": workflow, "output": str(target), "model": model,
            "seed": seed, "bundle_size": bundle_size, "coverage": coverage,
            "paid_targets": ["discovery-run", "consolidation-run", "classification-run"],
        }
    except (BewleyError, OSError) as exc:
        fail(command, exc if isinstance(exc, BewleyError) else BewleyError(str(exc), code="IO_ERROR"), json_flag)
        return
    finish(command, result)


@app.command("theory-explorer")
def codegen_theory_explorer(
    output: str = typer.Option(
        "qualitative-analysis/render_theory_explorer.py",
        "--output", "-o",
        help="Path to write the generated render script.",
    ),
    html_output: str = typer.Option(
        "qualitative-analysis/theory_explorer.html",
        "--html-output",
        help="Path the generated script will write the interactive HTML to.",
    ),
    title: Optional[str] = typer.Option(None, "--title", help="Page title for the explorer HTML."),
    human: bool = HumanOption,
) -> None:
    """Generate a Python script that renders an interactive D3 theory explorer as HTML.

    The generated script is standalone (stdlib only) and embeds a snapshot of
    the project's codes, hierarchy, links, and annotations. Regenerate when
    those change.
    """
    json_flag = should_emit_json(human)
    command = "codegen theory-explorer"
    project = get_project(command, json_flag)
    try:
        output_path = Path(output)
        html_path = Path(html_output)
        script_content = _build_theory_explorer_script(project, project.root, html_path, title)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(script_content, encoding="utf-8")
        result = {
            "script_path": str(output_path),
            "run_command": f"python {output_path}",
            "output_html": str(html_path),
        }
    except BewleyError as exc:
        fail(command, exc, json_flag)
        raise typer.Exit(2)
    if json_flag:
        finish(command, result)
    else:
        print(f"Script written to: {output_path}")
        print(f"Run: python {output_path}")
        print(f"Will produce: {html_path}")
